USE [Taller]
GO

CREATE PARTITION FUNCTION sucursal (int)  
AS RANGE LEFT FOR VALUES (1, 2);  

BEGIN TRANSACTION
CREATE PARTITION SCHEME [sucursal] AS PARTITION [sucursal] TO ([SucursalA], [SucursalB], [SucursalC])

ALTER TABLE [dbo].[Envio] DROP CONSTRAINT [PK__Envio__3213E83F30AB677F] WITH ( ONLINE = OFF )

ALTER TABLE [dbo].[Envio] ADD PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

CREATE CLUSTERED INDEX [ClusteredIndex_on_sucursal_637327751771491032] ON [dbo].[Envio]
(
	[idSucursal]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [sucursal]([idSucursal])


DROP INDEX [ClusteredIndex_on_sucursal_637327751771491032] ON [dbo].[Envio]

COMMIT TRANSACTION