insert into dbo.Producto (nombre, descripcion, foto, precio) values ('Pate - Cognac', 'Producto de calidad', 'data:image/png;base64,iVBORw0Klzc3O7OJpjqa+ZsAAAAASUVORK5CYII=', 11.22),
('Ice Cream - Strawberry', 'Producto de calidad', 'data:image/png;base64,iVBORjkpVJK3QAAAABJRU5ErkJggg==', 14.55),
('Chicken - Whole Roasting', 'Producto de calidad', 'data:image/png;base64,iVBORw0EOghMJb3AYt3K2ufolkg==', 12.43),
('Tart - Pecan Butter Squares', 'Producto de calidad', 'data:image/png;base64,icfbw/9D+/b9+VANbcvjMB1QURDsL/45xE/8/JVAVr3NVtvRY5cIEKW4J7NP737koB2wyiQXx4GBCDgYo7gPgTyNlQugMkDgAAPd9LkvTMtAAAAABJRU5ErkJggg==', 7.84),
('Veal - Chops, Split, Frenched', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhERVh0h1S8hmy7bJ0G+i60ECg2QXaIqVaqwttplXCSEMNDlZTqdEaEkyVbhprMBhwkXkCsCqcdHcOzxE8vsD2fhVr74vwRlXjVkJggg==', 14.3),
('Schnappes Peppermint - Walker', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0oiLVHBMbGymS7aUhIdoPNBf7Jjw/gQ77u4AAAAASUVORK5CYII=', 10.49),
('Sobe - Green Tea', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAIhSURBVDjLjZPfS1NxGMbPjX9Bl/0PXqQzIYIE2yKVjlgiQ1jSZgzo+K1eTC+mWvTmbB3dLEGumu34HFDhkJggg==', 11.91),
('Puree - Blackcurrant', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdZudcAjgZOOeJ3jkHJ0zggNpfYEZnU63wHeoAAAAASUVORK5CYII=', 8.62),
('Cheese - Mix', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAKjSURBVDjLrZLdT1JhHMfd6q6L7voT3NrEuQq6aTneOvqhLnPCxdjmqM12kN7SwTl5eX7qqurq2pra5eampqSGo2II=', 13.06),
('Pie Filling - Apple', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASW1hZ2VSZWFkeXHJZTwAAALcSURBVDjLjZJpSNNxHMb/VhTUi3piKthYOkJhYkz7lQdKYgqOw8rBKJFYLiraDTec1LjVOrSJ5CYII=', 13.75),
('Jicama', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUxUZpmvzDA29I3Bv7m5l7Dd8kw6XoJxL0wAAAABJRU5ErkJggg==', 7.87),
('Spice - Greek 1 Step', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdMLfrtkV62d2cz8hmVcDPbqfy6NlFRFHkA7AAAAAElFTkSuQmCC', 11.45),
('Longos - Penne With Pesto', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0Q5VNpGri0jOjUW9DD1sXOIHS+RzcbUWykqFfNnP3jlFTkSuQmCC', 9.39),
('Berry Brulee', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQzOnRjM1ifijfR2xOlM2jy1c+9X/OIlUgOn2F9dINwTdu7frc=', 14.74),
('Creme De Banane - Marie', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U2mw4j9PgnmiT2LbP2ZePP8OiAqyZHfdgY0AAAAASUVORK5CYII=', 7.59);
