-- productos sucursal A
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Sobe - Green Tea', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAIhSURBVDjLjZPfS1NxGMbPjX9Bl/0PXqQzIYIE2yKVjlgiQ1jSZgzo+K1eTC+mWvTmbB3dLEGumu34HFDhkJggg==', 59.4, 35);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Berry Brulee', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQzOnRjM1ifijfR2xOlM2jy1c+9X/OIlUgOn2F9dINwTdu7frc=', 46.49, 40);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Schnappes Peppermint - Walker', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0oiLVHBMbGymS7aUhIdoPNBf7Jjw/gQ77u4AAAAASUVORK5CYII=', 45.32, 20);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Ice Cream - Strawberry', 'Producto de calidad', 'data:image/png;base64,iVBORjkpVJK3QAAAABJRU5ErkJggg==', 48.27, 8);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Veal - Chops, Split, Frenched', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhERVh0h1S8hmy7bJ0G+i60ECg2QXaIqVaqwttplXCSEMNDlZTqdEaEkyVbhprMBhwkXkCsCqcdHcOzxE8vsD2fhVr74vwRlXjVkJggg==', 47.89, 33);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Sobe - Green Tea', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAIhSURBVDjLjZPfS1NxGMbPjX9Bl/0PXqQzIYIE2yKVjlgiQ1jSZgzo+K1eTC+mWvTmbB3dLEGumu34HFDhkJggg==', 49.44, 44);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Longos - Penne With Pesto', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0Q5VNpGri0jOjUW9DD1sXOIHS+RzcbUWykqFfNnP3jlFTkSuQmCC', 57.13, 13);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Jicama', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUxUZpmvzDA29I3Bv7m5l7Dd8kw6XoJxL0wAAAABJRU5ErkJggg==', 50.51, 11);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Puree - Blackcurrant', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdZudcAjgZOOeJ3jkHJ0zggNpfYEZnU63wHeoAAAAASUVORK5CYII=', 46.51, 1);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Pate - Cognac', 'Producto de calidad', 'data:image/png;base64,iVBORw0Klzc3O7OJpjqa+ZsAAAAASUVORK5CYII=', 47.24, 10);
