-- productos sucursal C
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Cheese - Mix', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAKjSURBVDjLrZLdT1JhHMfd6q6L7voT3NrEuQq6aTneOvqhLnPCxdjmqM12kN7SwTl5eX7qqurq2pra5eampqSGo2II=', 51.88, 75);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Spice - Greek 1 Step', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdMLfrtkV62d2cz8hmVcDPbqfy6NlFRFHkA7AAAAAElFTkSuQmCC', 55.19, 49);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Longos - Penne With Pesto', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0Q5VNpGri0jOjUW9DD1sXOIHS+RzcbUWykqFfNnP3jlFTkSuQmCC', 58.74, 83);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Schnappes Peppermint - Walker', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0oiLVHBMbGymS7aUhIdoPNBf7Jjw/gQ77u4AAAAASUVORK5CYII=', 50.23, 7);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Berry Brulee', 'Producto de calidad', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQzOnRjM1ifijfR2xOlM2jy1c+9X/OIlUgOn2F9dINwTdu7frc=', 45.82, 14);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Pate - Cognac', 'Producto de calidad', 'data:image/png;base64,iVBORw0Klzc3O7OJpjqa+ZsAAAAASUVORK5CYII=', 58.58, 2);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Tart - Pecan Butter Squares', 'Producto de calidad', 'data:image/png;base64,icfbw/9D+/b9+VANbcvjMB1QURDsL/45xE/8/JVAVr3NVtvRY5cIEKW4J7NP737koB2wyiQXx4GBCDgYo7gPgTyNlQugMkDgAAPd9LkvTMtAAAAABJRU5ErkJggg==', 47.94, 80);
insert into dbo.Producto (nombre, descripcion, foto, precioActual, existencias) values ('Chicken - Whole Roasting', 'Producto de calidad', 'data:image/png;base64,iVBORw0EOghMJb3AYt3K2ufolkg==', 50.83, 46);

